### ISSUE TITLE
Control validation behaviour through configuration file

### ISSUE THREAD

**Issue by ubiratansoares** [dotanuki-labs/canopus#6]
### Before getting started

- [x] I am **not** filing a bug/security report.
- [x] I have looked through the [open issues](https://github.com/dotanuki-labs/canopus/issues?q=is%3Aissue+is%3Aopen+) for a duplicate request and could not find it.

### What's the problem this feature/enhancement will solve?

On top of everything provided by #3, #4 and #5, we could also consider controlling the behaviour of `canopus` with a configuration file, for instance defined at `.github/canopus.toml`

### Describe the solution you'd like

There are a couple of behaviours that we could configure

```toml
# canopus.toml

# Controls whether we should validate only codeowners syntax and declared paths
# Eventually useful for PR checks
# default : false
offline-checks-only = true 

# Controls whether we should allow entries defining global project owners
# default : false
allow-global-owners = true
 
# Controls whether we should allow entries defining owners as email addresses
# default : false
github-owners-only = true

# Controls whether we should allow entries defining bot identities as owners
# default : false
allow-bot-owners = true 

# Controls whether entries should define Github teams as owners
# default : false
github-teams-owners-only = true
```
